# Generated by Django 4.1.3 on 2022-11-23 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="photo",
            field=models.ImageField(
                blank=True, default="media/user.png", null=True, upload_to=""
            ),
        ),
    ]
